import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

import { api } from "@/utils/api";
import Navbar from "@/components/shared/navbar";
import CreatePost from "@/components/feed/CreatePost";
import Posts from "@/components/feed/Posts";

export default function Home() {
  return (
    <>
      <Head>
        <title>Threads</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className=" mx-auto flex min-h-screen w-2/5 flex-col px-4 ">
        <CreatePost />
        <Posts/>
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();
  console.log(sessionData);

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
