import Head from "next/head";

import CreatePost from "@/components/feed/CreatePost";
import Posts from "@/components/feed/Posts";
import Navbar from "@/components/shared/navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Threads</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className=" mx-auto flex min-h-screen w-2/5 flex-col px-4 ">
        <CreatePost />
        <Posts/>
      </main>
    </>
  );
}

